package generators;

import ontology.NamedPoint;
import ontology.Preferences;
import ontology.Profile;
import ontology.Vehicle;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public enum ProfileFactory {
    ABSTRACT_PROFILE {
        @Override
        public Profile makeProfile() throws MalformedURLException {
            Collections.shuffle(NAMES);
            Collections.shuffle(URLS);
            Collections.shuffle(INTERESTS);

            final int id = RANDOM.nextInt(1_000_000);
            final int pointsNumber = RANDOM.nextInt(11);
            final String name = NAMES.stream().findAny().orElse("");
            final Vehicle vehicle = VehicleFactory.ABSTRACT_VEHICLE.makeVehicle(id);
            final URL socialAccount = new URL(URLS.stream().findAny().orElse(""));
            final String interests = INTERESTS.stream().findAny().orElse("");
            final List<NamedPoint> points = Stream
                    .generate(NamedPointFactory.ABSTRACT_NAMED_POINT::makeNamedPoint)
                    .limit(pointsNumber)
                    .collect(Collectors.toList());
            final Preferences preferences = PreferencesFactory.ABSTRACT_PREFERENCES.makePreferences();

            return new Profile(
                    id,
                    name,
                    vehicle,
                    socialAccount,
                    interests,
                    points,
                    preferences
            );
        }
    };

    private static final Random RANDOM = new Random();
    private static final List<String> NAMES = new ArrayList<>(Stream.of(
            "Fred Lichtenstein",
            "Dorothy Coverdale",
            "Alyce Loveall",
            "Jama Moorman",
            "Adina Mccook",
            "Marybeth Bennette",
            "Marielle Scribner",
            "Dalene Blue",
            "Maxwell Leask",
            "Kellie Ryan",
            "Emely Bleakley",
            "Augustina Davisson",
            "Scott Banton",
            "Jeanice Velasques",
            "Aurore Mclendon",
            "Nicole Wey",
            "Dannette Raia",
            "Renato Jepsen",
            "Lasonya Stem",
            "Young Medders",
            "Azalee Everson",
            "Kenna Kinchen",
            "Brigid Arndt",
            "Rachel Cramer",
            "Marlen Pridmore",
            "Trudie Alvares",
            "Herb Haight",
            "Emogene Gritton",
            "Deanne Condit",
            "Lucas Balogh",
            "Fredric Toma",
            "Leon Stow",
            "Michelle Metellus",
            "Andres Bratten",
            "Zachary Baltz",
            "Josefa Gump",
            "Dominique Barnwell",
            "Sidney Colquitt",
            "Hollie Sieber",
            "Solange Portales",
            "Olga Quesinberry",
            "Harris Fales",
            "Leigha Cauble",
            "Nana Credle",
            "Jonelle Patnode",
            "Jared Cid",
            "Colette Hohman",
            "Carry Marable",
            "Lala Curren",
            "Fe Parisien",
            "Lorraine Son",
            "Mirella Brekke",
            "Abdul Buendia",
            "Lorean Maul",
            "Adelaide Brand",
            "Armando Forness",
            "Annalee Toft",
            "Cordia Erion",
            "Xuan Janis",
            "Cinthia Eberhardt",
            "Darrel Brun",
            "Lynwood Baptiste",
            "Rochelle Howie",
            "Callie Hanney",
            "Andera Zych",
            "Don Doetsch",
            "Celestina Allan",
            "Coralee Nordquist",
            "Monroe Neubauer",
            "Warner Terpstra",
            "Glinda Broussard",
            "Isiah Oliveras",
            "Julieann Kam",
            "Ronni Merchant",
            "Amiee Wegener",
            "Ellan Pucci",
            "Antonio Heineman",
            "Love Kowalczyk",
            "Madeleine Cranford",
            "Orville Goldman",
            "Raeann Pou",
            "Cecelia Ludden",
            "Elaina Yanez",
            "Willian Schmaltz",
            "Deirdre Polk",
            "Tyler Straughan",
            "Lucretia Abasta",
            "Valrie Federico",
            "Hermelinda Sobus",
            "Junita Reisinger",
            "Noma Thibeault",
            "Osvaldo Vanover",
            "Joseph Branam",
            "Emilee Lemus",
            "Elenor Been",
            "Ashly Pigg",
            "Annice Bridgett",
            "Hwa Huizenga",
            "Craig Laakso",
            "Shakita Guthmiller"
    ).collect(Collectors.toList()));

    private static final List<String> URLS = Stream.of(
            "https://vk.com/Odin",
            "https://vk.com/Yeti",
            "https://vk.com/Buster",
            "https://vk.com/Mack",
            "https://vk.com/Tank",
            "https://vk.com/Kingpin",
            "https://vk.com/Richter",
            "https://vk.com/Dozer",
            "https://vk.com/Sledge",
            "https://vk.com/Brick",
            "https://vk.com/Crater",
            "https://vk.com/Nova",
            "https://vk.com/Thunder",
            "https://vk.com/Arcade",
            "https://vk.com/Crash",
            "https://vk.com/Nuke",
            "https://vk.com/Road Block",
            "https://vk.com/Collateral",
            "https://vk.com/Diesel",
            "https://vk.com/Prototype",
            "https://vk.com/Rascal",
            "https://vk.com/Cash",
            "https://vk.com/Duke",
            "https://vk.com/Dutchess",
            "https://vk.com/Viking",
            "https://vk.com/Nitro",
            "https://vk.com/Bull",
            "https://vk.com/Cowboy",
            "https://vk.com/Spike",
            "https://vk.com/Tombstone",
            "https://vk.com/Hazard",
            "https://vk.com/Bonzai",
            "https://vk.com/Geronimo",
            "https://vk.com/Trip",
            "https://vk.com/Spitfire",
            "https://vk.com/Loco",
            "https://vk.com/Blitz",
            "https://vk.com/Dice",
            "https://vk.com/Cobra",
            "https://vk.com/Wolverine",
            "https://vk.com/Gunner",
            "https://vk.com/Boomer",
            "https://vk.com/Android",
            "https://vk.com/Desperado",
            "https://vk.com/Psycho",
            "https://vk.com/Twitch",
            "https://vk.com/Pitbull",
            "https://vk.com/Rhino",
            "https://vk.com/Mustang",
            "https://vk.com/Werewolf",
            "https://vk.com/Sheriff",
            "https://vk.com/Wardog",
            "https://vk.com/Vandal",
            "https://vk.com/Smash",
            "https://vk.com/Hardcore",
            "https://vk.com/Zeus",
            "https://vk.com/Zed",
            "https://vk.com/Slim",
            "https://vk.com/Ranger",
            "https://vk.com/Pharaoh",
            "https://vk.com/Loki",
            "https://vk.com/Warlock",
            "https://vk.com/Specter",
            "https://vk.com/Shadow",
            "https://vk.com/Enigma",
            "https://vk.com/Claymore",
            "https://vk.com/Drifter",
            "https://vk.com/Ice",
            "https://vk.com/Nix",
            "https://vk.com/Demon",
            "https://vk.com/Hex",
            "https://vk.com/Cyclops",
            "https://vk.com/Zulu",
            "https://vk.com/Vampire",
            "https://vk.com/Zero",
            "https://vk.com/Echo",
            "https://vk.com/Alpha",
            "https://vk.com/Omega",
            "https://vk.com/Deadbolt",
            "https://vk.com/Neuro",
            "https://vk.com/Nightmare",
            "https://vk.com/Ghost",
            "https://vk.com/Snake Eyes",
            "https://vk.com/Spider",
            "https://vk.com/Lockdown",
            "https://vk.com/Stalker",
            "https://vk.com/Archer",
            "https://vk.com/Checkmate",
            "https://vk.com/Nighthawk",
            "https://vk.com/Deacon",
            "https://vk.com/Ace",
            "https://vk.com/Romeo",
            "https://vk.com/Atlas",
            "https://vk.com/Doc",
            "https://vk.com/Angel",
            "https://vk.com/Strings",
            "https://vk.com/Axle",
            "https://vk.com/Cargo",
            "https://vk.com/Saturn",
            "https://vk.com/Pox",
            "https://vk.com/Scarecrow",
            "https://vk.com/Whiskey",
            "https://vk.com/Scotch",
            "https://vk.com/Voodoo",
            "https://vk.com/Rogue",
            "https://vk.com/Sentinel",
            "https://vk.com/Prophet",
            "https://vk.com/Cairo",
            "https://vk.com/Freestyle",
            "https://vk.com/Athena",
            "https://vk.com/Raven",
            "https://vk.com/Baroness",
            "https://vk.com/Baron",
            "https://vk.com/Black Widow",
            "https://vk.com/Witch",
            "https://vk.com/Gypsy",
            "https://vk.com/Vixen",
            "https://vk.com/Pixie",
            "https://vk.com/Kitty",
            "https://vk.com/Syren",
            "https://vk.com/Foxtrot",
            "https://vk.com/Tilt",
            "https://vk.com/Digit",
            "https://vk.com/Null",
            "https://vk.com/Flak",
            "https://vk.com/Shift",
            "https://vk.com/Onyx",
            "https://vk.com/Shade",
            "https://vk.com/Phantom",
            "https://vk.com/Manticore",
            "https://vk.com/Fang",
            "https://vk.com/Prometheus",
            "https://vk.com/Shepherd",
            "https://vk.com/Vagabond",
            "https://vk.com/Corsair",
            "https://vk.com/Guru",
            "https://vk.com/Switchblade",
            "https://vk.com/Yankee",
            "https://vk.com/Sidewinder",
            "https://vk.com/Wizard",
            "https://vk.com/Blackbird",
            "https://vk.com/Falcon",
            "https://vk.com/Reaper",
            "https://vk.com/Tempest",
            "https://vk.com/Blade",
            "https://vk.com/Pheonix",
            "https://vk.com/Bone",
            "https://vk.com/Fiend",
            "https://vk.com/Flintlock",
            "https://vk.com/Junkyard",
            "https://vk.com/Panther",
            "https://vk.com/Ion",
            "https://vk.com/Barbarian",
            "https://vk.com/Condor",
            "https://vk.com/Vanguard",
            "https://vk.com/Paladin",
            "https://vk.com/Knight",
            "https://vk.com/Amazon",
            "https://vk.com/Shark",
            "https://vk.com/Piranha",
            "https://vk.com/Exile",
            "https://vk.com/Dragon",
            "https://vk.com/Saint",
            "https://vk.com/Spartan",
            "https://vk.com/Solar",
            "https://vk.com/Ares",
            "https://vk.com/Nemesis",
            "https://vk.com/Valkyrie",
            "https://vk.com/Devil",
            "https://vk.com/Bandit",
            "https://vk.com/Saber",
            "https://vk.com/Raider",
            "https://vk.com/Scythe",
            "https://vk.com/Razor",
            "https://vk.com/Nomad",
            "https://vk.com/Warlord",
            "https://vk.com/Outlaw",
            "https://vk.com/Chaos",
            "https://vk.com/Immortal",
            "https://vk.com/Rebel",
            "https://vk.com/Hawk",
            "https://vk.com/Cosmic",
            "https://vk.com/Samurai",
            "https://vk.com/Glacier",
            "https://vk.com/Pandora",
            "https://vk.com/Wasp",
            "https://vk.com/Inferno",
            "https://vk.com/Dust",
            "https://vk.com/Joker",
            "https://vk.com/Blackjack",
            "https://vk.com/Hammer",
            "https://vk.com/Archangel",
            "https://vk.com/Cable",
            "https://vk.com/Praetor",
            "https://vk.com/Aztec",
            "https://vk.com/Jester",
            "https://vk.com/Raptor",
            "https://vk.com/Rook",
            "https://vk.com/Ozone",
            "https://vk.com/Nano",
            "https://vk.com/Renegade",
            "https://vk.com/Scorch",
            "https://vk.com/Paradox",
            "https://vk.com/Magnum",
            "https://vk.com/Scarab",
            "https://vk.com/Luna",
            "https://vk.com/Fenway",
            "https://vk.com/Zombie",
            "https://vk.com/Delta",
            "https://vk.com/Minotaur",
            "https://vk.com/Hydra",
            "https://vk.com/Ironhide",
            "https://vk.com/Grunt",
            "https://vk.com/Shroud",
            "https://vk.com/Nightingale",
            "https://vk.com/Mantis",
            "https://vk.com/Volley",
            "https://vk.com/Grinder",
            "https://vk.com/Overdrive",
            "https://vk.com/Wraith",
            "https://vk.com/Gryphon",
            "https://vk.com/Shrapnel",
            "https://vk.com/Gen",
            "https://vk.com/Trauma",
            "https://vk.com/Gearshift",
            "https://vk.com/Mayhem",
            "https://vk.com/Templar",
            "https://vk.com/Gadget",
            "https://vk.com/Vigilante",
            "https://vk.com/Chef",
            "https://vk.com/Javelin",
            "https://vk.com/Tomahawk",
            "https://vk.com/Jazz",
            "https://vk.com/Sideswipe",
            "https://vk.com/Mirage",
            "https://vk.com/Warpath",
            "https://vk.com/Slingshot",
            "https://vk.com/Vortex",
            "https://vk.com/Sandman",
            "https://vk.com/Goliath",
            "https://vk.com/Marauder",
            "https://vk.com/Hurricane",
            "https://vk.com/Princess",
            "https://vk.com/Harpy",
            "https://vk.com/Medusa",
            "https://vk.com/Artemis",
            "https://vk.com/Thumper",
            "https://vk.com/Houdini",
            "https://vk.com/Alcatraz",
            "https://vk.com/Jackpot",
            "https://vk.com/Lunatic",
            "https://vk.com/Radical",
            "https://vk.com/Pinpoint",
            "https://vk.com/Blindfire",
            "https://vk.com/Wildfire",
            "https://vk.com/Whiplash",
            "https://vk.com/Breakdown",
            "https://vk.com/Riptide",
            "https://vk.com/Tornado",
            "https://vk.com/Kraken",
            "https://vk.com/Leviathan",
            "https://vk.com/Iris",
            "https://vk.com/Pirate",
            "https://vk.com/Ghoul",
            "https://vk.com/Mako",
            "https://vk.com/Dingo",
            "https://vk.com/Gladiator",
            "https://vk.com/Bishop",
            "https://vk.com/Preacher",
            "https://vk.com/Rabbit",
            "https://vk.com/Apollo",
            "https://vk.com/Orion",
            "https://vk.com/Casper",
            "https://vk.com/Mercury",
            "https://vk.com/Highrise",
            "https://vk.com/Monarch",
            "https://vk.com/Empress",
            "https://vk.com/Pinball",
            "https://vk.com/Clutch",
            "https://vk.com/Turntable",
            "https://vk.com/Prodigy",
            "https://vk.com/Buzzsaw",
            "https://vk.com/Glitch",
            "https://vk.com/Zealot",
            "https://vk.com/Gecko",
            "https://vk.com/Ballistic",
            "https://vk.com/Diablo",
            "https://vk.com/Maniac",
            "https://vk.com/Quake",
            "https://vk.com/Magma",
            "https://vk.com/Architect",
            "https://vk.com/Jackal",
            "https://vk.com/Aero",
            "https://vk.com/Airwave",
            "https://vk.com/Airborne",
            "https://vk.com/Alpine",
            "https://vk.com/Altitude",
            "https://vk.com/Ambush",
            "https://vk.com/Armadillo",
            "https://vk.com/Audio",
            "https://vk.com/Avalanche",
            "https://vk.com/Banshee",
            "https://vk.com/Barricade",
            "https://vk.com/Basilisk",
            "https://vk.com/Blindfold",
            "https://vk.com/Blizzard",
            "https://vk.com/Blowtorch",
            "https://vk.com/Burnout",
            "https://vk.com/Countdown",
            "https://vk.com/Crossfire",
            "https://vk.com/Crusader",
            "https://vk.com/Cypher",
            "https://vk.com/Dryad",
            "https://vk.com/Feral",
            "https://vk.com/Freefall",
            "https://vk.com/Frostbite",
            "https://vk.com/Havok",
            "https://vk.com/Iceberg",
            "https://vk.com/Jinx",
            "https://vk.com/Landslide",
            "https://vk.com/Meltdown",
            "https://vk.com/Outback",
            "https://vk.com/Payload",
            "https://vk.com/Overload",
            "https://vk.com/Skydive",
            "https://vk.com/Torpedo",
            "https://vk.com/Tripwire",
            "https://vk.com/Wreckage",
            "https://vk.com/Sovereign",
            "https://vk.com/Buckshot",
            "https://vk.com/Crusher",
            "https://vk.com/Carbon",
            "https://vk.com/Epsilon",
            "https://vk.com/Patch",
            "https://vk.com/Cutthroat",
            "https://vk.com/Outbreak",
            "https://vk.com/Trigger",
            "https://vk.com/Thor",
            "https://vk.com/Sparrow",
            "https://vk.com/Rusty",
            "https://vk.com/Hollow",
            "https://vk.com/Frozen",
            "https://vk.com/Tuner",
            "https://vk.com/Legend",
            "https://vk.com/Hazmat",
            "https://vk.com/Liquid",
            "https://vk.com/Freight",
            "https://vk.com/Steel",
            "https://vk.com/Pilgrim",
            "https://vk.com/Druid",
            "https://vk.com/Volt"
    ).collect(Collectors.toList());

    private static final List<String> INTERESTS = Stream.of(
            "Mountain Bikes",
            "Road Bikes",
            "Boats & Watercraft",
            "Campers & RVs",
            "Classic Vehicles",
            "Commercial Vehicles",
            "Cargo Trucks & Trailers",
            "Custom & Performance Vehicles",
            "Hybrid & Alternative Vehicles",
            "Electric & Plug-In Vehicles",
            "Microcars & City Cars",
            "Motorcycles",
            "Off-Road Vehicles",
            "Personal Aircraft",
            "Scooters & Mopeds",
            "Trucks & SUVs",
            "SUVs",
            "Trucks",
            "Vans & Minivans",
            "Vehicle Brands",
            "Acura",
            "Audi",
            "BMW",
            "Bentley",
            "Buick",
            "Cadillac",
            "Chevrolet",
            "Chrysler",
            "Citroën",
            "Dodge",
            "Ferrari",
            "Fiat",
            "Alfa Romeo",
            "Ford",
            "GM-Daewoo",
            "GMC",
            "Honda",
            "Hummer",
            "Hyundai",
            "Isuzu",
            "Jaguar",
            "Jeep",
            "Kia",
            "Lamborghini",
            "Land Rover",
            "Lexus",
            "Lincoln",
            "Maserati",
            "Mazda",
            "Mercedes-Benz",
            "Mercury",
            "Mini",
            "Mitsubishi",
            "Nissan",
            "Infiniti",
            "Peugeot",
            "Pontiac",
            "Porsche",
            "Renault-Samsung",
            "Rolls-Royce",
            "SEAT",
            "Saab",
            "Saturn",
            "Subaru",
            "Suzuki",
            "Toyota",
            "Scion",
            "Vauxhall-Opel",
            "Volkswagen",
            "Volvo",
            "Vehicle Codes & Driving Laws",
            "Vehicle & Traffic Safety",
            "Vehicle Licensing & Registration",
            "Driving Instruction & Driver Education",
            "Vehicle Maintenance",
            "Vehicle Parts & Accessories",
            "Auto Exterior",
            "Auto Interior",
            "Engine & Transmission",
            "Vehicle Fuels & Lubricants",
            "Vehicle Wheels & Tires",
            "Vehicle Shopping",
            "Fuel Economy & Gas Prices",
            "Vehicle Specs, Reviews & Comparisons",
            "Vehicle Shows",
            "category::Beauty & Fitness",
            "Beauty Pageants",
            "Body Art",
            "Cosmetology & Beauty Professionals",
            "Face & Body Care",
            "Hygiene & Toiletries",
            "Make-Up & Cosmetics",
            "Perfumes & Fragrances",
            "Skin & Nail Care",
            "Fashion & Style",
            "Fashion Designers & Collections",
            "Fashion Modeling",
            "Fitness",
            "Bodybuilding",
            "Fitness Equipment & Accessories",
            "Fitness Instruction & Personal Training",
            "Gyms & Health Clubs",
            "Yoga & Pilates",
            "Hair Care",
            "Spas & Beauty Services",
            "Massage Therapy",
            "category::Books & Literature",
            "Book Retailers",
            "Children's Literature",
            "E-Books",
            "Fan Fiction",
            "Literary Classics",
            "Magazines",
            "Poetry",
            "Writers Resources",
            "category::Games",
            "Arcade & Coin-Op Games",
            "Board Games",
            "Chess & Abstract Strategy Games",
            "Miniatures & Wargaming",
            "Card Games",
            "Collectible Card Games",
            "Computer & Video Games",
            "Action & Platform Games",
            "Adventure Games",
            "Casual Games",
            "Driving & Racing Games",
            "Fighting Games",
            "Gaming Media & Reference",
            "Game Cheats & Hints",
            "Music & Dance Games",
            "Shooter Games",
            "Simulation Games",
            "Business & Tycoon Games",
            "City Building Games",
            "Life Simulation Games",
            "Vehicle Simulators",
            "Sports Games",
            "Sports Management Games",
            "Strategy Games",
            "Video Game Development",
            "Video Game Emulation",
            "Video Game Retailers",
            "Dice Games",
            "Educational Games",
            "Family-Oriented Games & Activities",
            "Drawing & Coloring",
            "Online Games",
            "Massive Multiplayer",
            "Party Games",
            "Puzzles & Brainteasers",
            "Roleplaying Games",
            "Table Games",
            "Billiards",
            "Table Tennis",
            "Tile Games",
            "Word Games",
            "Pets & Animals",
            "Animal Products & Services",
            "Animal Welfare",
            "Pet Food & Supplies",
            "Veterinarians",
            "Pets",
            "Birds",
            "Cats",
            "Dogs",
            "Exotic Pets",
            "Fish & Aquaria",
            "Horses",
            "Rabbits & Rodents",
            "Reptiles & Amphibians",
            "Wildlife"
    ).collect(Collectors.toList());

    public abstract Profile makeProfile() throws MalformedURLException;
}
